### ISSUE TITLE
[PE-D][Tester B] bug in the add feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-3/tp#109]
Unable to insert modules that have '/' in the module name.

![image.png](https://raw.githubusercontent.com/EugeneChanJiajun/ped/main/files/5a532fb6-097e-4e80-86d5-3ba1bd558fc9.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: EugeneChanJiajun/ped#3

**Comment by fungg0** [comment]
CS2113T does not require a slash.
