### ISSUE TITLE
[PE-D][Tester B] Init functionality issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-3/tp#111]
Not sure if this is as intended but only numeric values can be used for current semester and graduating semester. This might cause some confusion for the user.

![image.png](https://raw.githubusercontent.com/EugeneChanJiajun/ped/main/files/360602b7-1818-44df-a4a1-c971f0141e1b.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: EugeneChanJiajun/ped#4

**Comment by fungg0** [comment]
We have specified inside the UG the requirements of the input to only be numerical for current and graduating semesters. Any exceptions will be dealt with beyond v2.1
