### ISSUE TITLE
[PE-D][Tester F] Non-inclusion for common naming characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-3/tp#116]
Name argument does not welcome common name arguments such as backslashes ('/'). Names such as s/o or d/o may require such characters.

![image.png](https://raw.githubusercontent.com/nickczh/ped/main/files/38de4afa-b285-4685-844e-14564c22765a.png)

However, great efforts in trying to catch invalid characters.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nickczh/ped#2

**Comment by fungg0** [comment]
It is specified in the UG that input for name currently only accepts English alphabets.

**Comment by sxfoo** [comment]
The name is more of a personalisation for the program. It is not necessary to put in your full legal name, and is meant for like a simple nick name/ username for the program to address you. Therefore, we only restrict it to alphabetical characters, and optionally having spaces in between.
