### ISSUE TITLE
[PE-D][Tester D] Help Message Not Informative Enough

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-3/tp#122]
![image.png](https://raw.githubusercontent.com/ZhouJunmin/ped/main/files/de3b4b65-5ca1-4ee4-879c-01b3621ce21f.png)
When adding a course to the planner, the "w/<WHEN>" is not clear enough for user. The user may want to key in commands like "year 1 sem 1" instead of the semester number. Also, the semester number corresponding to "year n semester m" is also better to be specifed to user as well, to use the app properly.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ZhouJunmin/ped#2

**Comment by fungg0** [comment]
We have specified the requirements in the user guide. Please do give it a read next time while using the app :)
