### ISSUE TITLE
[PE-D][Tester F] Allowing of similar variants of course to be taken under the same semester

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-3/tp#131]
Perhaps this can be better improved if the same variants cannot be added in same semester?

![image.png](https://raw.githubusercontent.com/nickczh/ped/main/files/e6c84a96-a868-47d2-a1ec-bb30f688ca1b.png)

These course codes are the same variant and should not be taken together.

![image.png](https://raw.githubusercontent.com/nickczh/ped/main/files/f115c67e-702e-41c8-b42a-4679f89bb439.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nickczh/ped#5

**Comment by fungg0** [comment]
We will implement a functionality to check this beyond v2.1. It is out of scope for v2.1

**Comment by sxfoo** [comment]
Currently, this will be a difficult feature to implement. The NUS mods API do not give an easy way to differentiate between variants as they are still considered different modules.
