### ISSUE TITLE
[PE-D][Tester F] Documentation markdown not rendered correctly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-3/tp#136]
![image.png](https://raw.githubusercontent.com/nickczh/ped/main/files/fc69ff41-27d9-4441-bbd8-e9f9ff5d121e.png)

What is [!IMPORTANT]?

Is it suppose to be a visual symbol?

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: nickczh/ped#7

**Comment by fungg0** [comment]
The markdown shows properly on the github page, but does not translate properly when saved as pdf.
