### ISSUE TITLE
Remove comments which are obvious

### ISSUE THREAD

**Issue by madhanse** [AY2324S2-CS2113-W14-3/tp#92]
@sxfoo 
![image](https://github.com/AY2324S2-CS2113-W14-3/tp/assets/69302316/edf43ae9-5bbb-4049-9f6b-d87b219e9820)
@ThawTunZan 
![image](https://github.com/AY2324S2-CS2113-W14-3/tp/assets/69302316/caf61734-1f16-4143-a2c8-297fa11509af)

Please remove the comments which are understandable from that specific line of code to improve code quality. Above is one of the examples from the ones assigned

**Comment by sxfoo** [comment]
Both comments removed by PR #95 and PR #94
